// Generated by CoffeeScript 1.4.0
'use strict';

var Primus, http, out, primus, server;

out = __dirname + '/public/javascripts' + '/primusClientLib.js';

console.log('Building primus client library to be served to the client as ' + out);

http = require("http");

Primus = require('primus');

server = require('http').createServer();

primus = new Primus(server, {
  transformer: 'websockets'
});

primus.library();

primus.save(out);
