// Generated by CoffeeScript 1.6.3
var docDataDir, files, logging, myWriter, util;

logging = require('./logging');

myWriter = require('./writer');

util = require('./util');

docDataDir = 'docData';

exports.docDataDir = docDataDir;

files = {};

exports.write = function(inputFileName, dataType, data) {
  var nameBase, now, writer;
  if (files[inputFileName] == null) {
    files[inputFileName] = {};
  }
  if (files[inputFileName][dataType] == null) {
    logging.cond("opening writer for " + dataType, 'dataWriter');
    util.mkdir(docDataDir, inputFileName);
    now = new Date();
    nameBase = docDataDir + '/' + inputFileName + '/' + dataType + '-' + now.toISOString() + '.out';
    writer = new myWriter(nameBase);
    logging.cond("Data writing for [" + inputFileName + "], [" + dataType + "] is going to " + nameBase, 'dataWriter');
    files[inputFileName][dataType] = writer;
  }
  files[inputFileName][dataType].write(data);
  return true;
};

exports.close = function(inputFileName) {
  var writer;
  logging.cond("closing writers for " + inputFileName, 'dataWriter');
  for (writer in files[inputFileName]) {
    logging.cond("writer to close: " + writer, logging.cond);
    files[inputFileName][writer].close();
  }
  return delete files[inputFileName];
};
