// Generated by CoffeeScript 1.6.3
var exec, logging, util;

util = require('./util');

logging = require('./logging');

exec = require('child_process').exec;

exports.storePdfMetaData = function(localCopy, docLogger) {
  var execCommand;
  util.timelog("Getting pdf file metadata using pdfinfo");
  execCommand = 'pdfinfo -meta' + ' ';
  execCommand += '"' + localCopy + '"';
  return exec(execCommand, function(error, stdout, stderr) {
    var meta;
    docLogger.info(execCommand + "'s stdout: " + stdout);
    docLogger.info(execCommand + "'s stderr: " + stderr);
    if (error !== null) {
      return docLogger.error(execCommand + "'sexec error: " + error);
    } else {
      util.timelog("Getting pdf file metadata using pdfinfo", docLogger);
      return meta = {
        'raw': stdout,
        'stderr': stderr
      };
    }
  });
};
