// Generated by CoffeeScript 1.6.3
var elasticsearch, es;

elasticsearch = require("elasticsearch");

/*

# Connect to localhost:9200 and use the default settings
es = new elasticsearch.Client()

# Connect the client to two nodes, requests will be
# load-balanced between them using round-robin
client = elasticsearch.Client(hosts: [
  "elasticsearch1:9200"
  "elasticsearch2:9200"
])
*/


/*
# Connect to this host using https, basic auth,
# a path prefix, and static query string values
client = new elasticsearch.Client(host: "https://user:password@elasticsearch1/search?app=blog")
*/


es = elasticsearch.Client({
  host: "localhost:9200",
  sniffOnStart: true,
  sniffInterval: 300000,
  apiVersion: '1.0'
});

es.create({
  index: 'meta',
  type: 'in-text-appearance',
  body: {
    text: 'bla',
    article: 'bla'
  }
}, function(error) {
  if (error != null) {
    return console.error(error);
  }
});
