// Generated by CoffeeScript 1.4.0

exports.errorHandler = function(error, request, response, next) {
  var etext;
  console.error('Error thrown for request: ' + request.url);
  if (error.stack != null) {
    etext = error.stack;
  } else {
    etext = error;
  }
  console.error(etext);
  console.log('Sending error message to client');
  return response.send(500, {
    error: error
  });
};
