// Generated by CoffeeScript 1.6.3
var markers, util;

util = require('./util');

markers = {};

exports.load = function() {
  var csvConverter, csvFile, csvToJsonConverter;
  util.timelog('Loading markers');
  csvToJsonConverter = require('csvtojson').core.Converter;
  csvConverter = new csvToJsonConverter();
  csvConverter.on("end_parsed", function(jsonFromCss) {
    return markers = jsonFromCss;
  });
  csvFile = './markers.csv';
  csvConverter.from(csvFile);
  return util.timelog('Loading markers');
};
