// Generated by CoffeeScript 1.4.0
var Token, TokenGroup, a, b, util;

util = require('./util');

Token = (function() {
  var types;

  types = ['word', 'punctuation,', 'superscriptComment'];

  function Token(type) {
    var error;
    this.type = type;
    if (!util.isAnyOf(this.type, types)) {
      error = new Error('invalid token type encountered on token creation');
      console.log(error.stack);
      throw error;
    }
  }

  return Token;

})();

TokenGroup = (function() {

  function TokenGroup() {
    this.tokens = [];
  }

  TokenGroup.prototype.add = function(token) {
    if (!(token instanceof Token)) {
      util.objectViolation('TokenGroup can only include Token objects');
    }
    return this.tokens.push(token);
  };

  TokenGroup.prototype.getAll = function() {
    return this.tokens;
  };

  return TokenGroup;

})();

a = new Token('word');

b = new TokenGroup;

b.add(a);

console.log(b);
