// Generated by CoffeeScript 1.4.0

require("fs");

require("jsdom");

exports.serveOutput = function(text, name, res) {
  var outputFile;
  outputFile = './local-copies/' + 'output/' + name + '.html';
  return fs.writeFile(outputFile, "aaa", function(err) {
    if (err != null) {
      res.send(500);
      throw err;
    }
    console.log('Output saved');
    console.log('Sending response....');
    return res.sendfile(outputFile);
  });
};
