// Generated by CoffeeScript 1.6.3
var fs, hookElementTextPos, hookId, logging, outputTemplate, util;

util = require('./util');

logging = require('./logging');

fs = require('fs');

outputTemplate = fs.readFileSync('outputTemplate/index.html').toString();

hookId = 'hookPoint';

hookElementTextPos = outputTemplate.indexOf(">", outputTemplate.indexOf('<span id="' + hookId + '"')) + 1;

exports.serveOutput = function(html, name, res, docLogger) {
  var outputFile, outputHtml;
  outputFile = '../local-copies/' + 'output/' + name + '.html';
  outputHtml = outputTemplate.slice(0, hookElementTextPos).concat(html, outputTemplate.slice(hookElementTextPos));
  util.timelog('Saving serialized output to file');
  return fs.writeFile(outputFile, outputHtml, function(err) {
    if (err != null) {
      res.send(500);
      throw err;
    }
    util.timelog('Saving serialized output to file', docLogger);
    docLogger.info('Sending response....');
    util.timelog('from upload to serving', docLogger);
    return res.sendfile(name + '.html', {
      root: '../local-copies/' + 'output/'
    });
  });
};
