// Generated by CoffeeScript 1.4.0
'use strict';

var Primus;

Primus = require('primus');

exports.start = function(server) {
  var logSpark, primus, sparks;
  primus = new Primus(server, {
    transformer: 'websockets'
  });
  sparks = 0;
  logSpark = function(spark, message) {
    var sparksCount;
    sparksCount = sparks + ' ' + 'active sparks';
    return console.log('Primus: ' + spark.address.ip + ' (id ' + spark.id + ') ' + message + ' ' + '[' + sparksCount + ']');
  };
  setTimeout((function() {
    if (sparks !== 0) {
      console.log('Primus: broadcasting \'up\' message to all quick to connect clients');
      return primus.write("ServerRestarted");
    }
  }), 2000);
  primus.on('connection', function(spark) {
    sparks += 1;
    return logSpark(spark, 'connected on port ' + spark.address.port);
  });
  return primus.on('disconnection', function(spark) {
    sparks -= 1;
    return logSpark(spark, 'disconnected');
  });
};
