// Generated by CoffeeScript 1.4.0

exports.calcMostFrequentFont = function(input) {
  return [50, 'font-family'];
};

exports.guessParagraphLeft = function(input) {
  return 30;
};

exports.build = function(input) {
  return input;
};
