// Generated by CoffeeScript 1.6.3
var logging;

logging = require('./logging');

exports.calcMostFrequentFont = function(input) {
  return [50, 'font-family'];
};

exports.guessParagraphLeft = function(input) {
  return 30;
};

exports.build = function(input) {
  return input;
};
