// Generated by CoffeeScript 1.6.3
var crypto, fs, logging, riak, util;

util = require('./util');

logging = require('./logging');

riak = require('riak-js').getClient({
  host: "localhost",
  port: "8098"
});

fs = require('fs');

crypto = require('crypto');

exports.store = function(bucket, filename, file, docLogger) {
  var fileContent, hash, hasher;
  util.timelog("storing file to clustered storage");
  hasher = crypto.createHash('md5');
  fileContent = fs.readFileSync(file);
  util.timelog("hashing input file");
  hasher.update(fileContent);
  hash = hasher.digest('hex');
  util.timelog("hashing input file");
  console.log(hash);
  return riak.save(bucket, filename, fileContent, function(error) {
    util.timelog("storing file to clustered storage", docLogger);
    if (error != null) {
      return docLogger.error("failed storing file to clustered storage");
    }
  });
};

exports.fetch = function(bucket, filename, callback) {
  util.timelog("fetching file from clustered storage");
  return riak.get(bucket, filename, function(error, fileContent) {
    if (error != null) {
      console.error("failed fetching file from clustered storage");
      return false;
    } else {
      util.timelog("fetching file from clustered storage");
      console.log(fileContent);
      return callback(fileContent);
    }
  });
  /*
  riak.get('pdf', 'tXqIBGiBR5aMgxBQBOVY', (error, fileContent) ->
    if error
      logging.log(error)
    else
      logging.log(fileContent)
    fs.writeFileSync('back-from-riak.pdf', fileContent))
  */

};
