// Generated by CoffeeScript 1.6.3
var deriveInitialCaps, deriveUpperCase, expand, expected;

expected = ['Introduction', 'Method', 'Methodology', 'Discussion', 'General Discussion', 'Results', 'Conclusion', 'References', 'Limitation'];

deriveUpperCase = function(base) {
  var variants;
  variants = [];
  base.forEach(function(item) {
    return variants.push(item.toUpperCase());
  });
  return variants;
};

deriveInitialCaps = function(base) {
  var variants;
  variants = [];
  base.forEach(function(item) {
    return variants.push(item.substring(1));
  });
  return variants;
};

expand = function(expected) {
  return expected.concat(deriveUpperCase(expected), deriveInitialCaps(expected));
};

module.exports = expand(expected);
