// Generated by CoffeeScript 1.6.3
var dataWriter, expected, tripleIterator;

dataWriter = require('../../data/dataWriter');

expected = require('./expected');

tripleIterator = function(tokens, func) {
  var curr, i, next, prev, _results;
  i = 1;
  _results = [];
  while (i < tokens.length - 1) {
    prev = tokens[i - 1];
    curr = tokens[i];
    next = tokens[i + 1];
    func(prev, curr, next);
    _results.push(i = i + 1);
  }
  return _results;
};

module.exports = function(name, tokens) {
  var headers, regularTokens;
  console.dir(expected);
  headers = [];
  regularTokens = tokens.filter(function(token) {
    return token.metaType === 'regular';
  });
  return tripleIterator(regularTokens, function(prev, curr, next) {
    var _ref;
    if (expected.indexOf(curr.text) === -1) {
      return;
    }
    if ((_ref = curr["case"]) !== 'upper' && _ref !== 'title') {
      return;
    }
    return dataWriter.write(name, 'headers', "token id " + curr.id + ": " + curr.text);
  });
};
