// Generated by CoffeeScript 1.6.3
var dataWriter, exec, logging, util;

exec = require("child_process").exec;

util = require('../util/util');

logging = require('../util/logging');

dataWriter = require('../data/dataWriter');

module.exports = function(cmd, callback) {
  return exec(cmd, function(error, stdout, stderr) {
    if (stderr) {
      console.log("stderr: " + stderr);
    }
    if (error !== null) {
      console.error("execution of shell command " + cmd + " failed with error: \n " + error);
      callback(error, stdout, stderr);
    }
    return callback(null, stdout, stderr);
  });
};
