// Generated by CoffeeScript 1.6.3
var dataWriter, exec, logging, util;

exec = require("child_process").execFile;

util = require('../util/util');

logging = require('../util/logging');

dataWriter = require('../data/dataWriter');

module.exports = function(executable, executalbeParams, callback) {
  return exec(executable, executalbeParams, function(error, stdout, stderr) {
    if (stderr) {
      console.log("stderr: " + stderr);
    }
    if (error !== null) {
      console.error("execution of binary/shell file " + executable + " failed with error: \n " + error);
      callback(false);
    }
    return callback(true);
  });
};
