// Generated by CoffeeScript 1.6.3
var log, nconf, testGraylog2, testLogio, testWinstonLogstash, tty, winston,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

nconf = require('nconf');

exports.cond = function(message, tag) {
  var enabledTags;
  enabledTags = nconf.get('tagsEnabled');
  if (__indexOf.call(enabledTags, tag) >= 0) {
    return console.log(message);
  }
};

winston = require('winston');

log = function(level, msgOrObj) {
  return winston.log(level, msgOrObj);
};

exports.log = function(msgOrObj) {
  return log('info', msgOrObj);
};

exports.warn = function(msgOrObj) {
  return log('warn', msgOrObj);
};

exports.error = function(msgOrObj) {
  return log('error', msgOrObj);
};

exports.init = function() {};

tty = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[36m',
  magenta: '\x1b[35m',
  bold: '\x1b[1m',
  italics: '\x1b[3m',
  end: '\x1b[0m'
};

exports.bold = function(text) {
  return tty.bold + text + tty.end;
};

exports.italics = function(text) {
  return tty.italics + text + tty.end;
};

exports.logBold = function(text) {
  return console.log(tty.bold + text + tty.end);
};

exports.logGreen = function(text, bold) {
  if (bold != null) {
    return console.log(tty.green + tty.bold + text + tty.end);
  } else {
    return console.log(tty.green + text + tty.end);
  }
};

exports.logYellow = function(text) {
  return console.log(tty.yellow + text + tty.end);
};

exports.logRed = function(text) {
  return console.log(tty.red + text + tty.end);
};

exports.logBlue = function(text) {
  return console.log(tty.blue + text + tty.end);
};

exports.logPerf = function(text) {
  return console.log(tty.magenta + text + tty.end);
};

testLogio = function() {
  require('winston-logio');
  winston.add(winston.transports.Logio, {
    port: 28777,
    node_name: 'nodejs',
    host: '127.0.0.1'
  });
  return winston.log('info', 'Hello to logio');
};

testGraylog2 = function() {
  winston.add(require('winston-graylog2').Graylog2, {});
  return winston.log('info', 'Hello to graylog2');
};

testWinstonLogstash = function() {
  log = function(level, msgOrObj) {
    if (typeof msgOrObj !== 'object') {
      return winston.log(level, msgOrObj);
    } else {
      return winston.log(level, msgOrObj);
    }
  };
  exports.log = function(msgOrObj) {
    return log('info', msgOrObj);
  };
  exports.warn = function(msgOrObj) {
    return log('warn', msgOrObj);
  };
  return exports.init = function() {
    require('winston-logstash');
    winston.remove(winston.transports.Console);
    return winston.add(winston.transports.Logstash, {
      port: 28777,
      node_name: 'nodejs',
      host: '127.0.0.1'
    });
  };
};
