// Generated by CoffeeScript 1.6.3
var dataWriter, exec, logging, util;

util = require('./util');

logging = require('./logging');

dataWriter = require('../data/dataWriter');

exec = require('child_process').exec;

module.exports = function(context, localCopy, docLogger, params) {
  var dataType, description, execCommand;
  execCommand = params.execCommand;
  dataType = params.dataType;
  description = params.description;
  util.timelog(context, description);
  execCommand += ' ' + '"' + localCopy + '"';
  return exec(execCommand, function(error, stdout, stderr) {
    var meta;
    dataWriter.write(context, dataType, execCommand + "'s stdout: \n" + stdout);
    dataWriter.write(context, dataType, execCommand + "'s stderr: \n" + stderr);
    if (error !== null) {
      return dataWriter.write(context, dataType, execCommand + "'sexec error: " + error);
    } else {
      util.timelog(context, description);
      return meta = {
        'raw': stdout,
        'stderr': stderr
      };
    }
  });
};
