util = require '../util'
logging = require '../logging' 
docMeta = require '../docMeta'
storage = require '../storage'
getFromUrl = require 'request'
fs = require 'fs'
require 'stream'
winston = require 'winston'
exec = require("child_process").exec


executable = "pdf2htmlEX"
executalbeParams = "--embed-css=0 --embed-font=0 --embed-image=0 --embed-javascript=0"

#
# * Handles the conversion from pdf to html, and forwards to next stage.
# 

exports.go = (req, res) ->

  #
  # * Fetches the upload from Ink File Picker (writing it into local file).
  # * If it works - invoke the passed along callback function.
  # 
  fetch = (inkUrl, baseFileName, callOnSuccess) ->
    
    #outFile = inkUrl + '.pdf';
    outFile = "../local-copies/" + "pdf/" + baseFileName + ".pdf"
    download = getFromUrl(inkUrl, (error, response, body) ->
      if (not error and response.statusCode is 200)
          callOnSuccess(outFile, docLogger)
      else
        console.log "fetching from InkFilepicker returned http status " + response.statusCode
        if error
          logging.log "fetching from InkFilepicker returned error " + error 
    ).pipe(fs.createWriteStream(outFile))

  redirectToShowHtml = (redirectString) ->
    logging.log "Passing html result to next level handler, by redirecting to: " + redirectString
    res.writeHead 301,
      Location: redirectString

    res.end()
  redirectToExtract = (redirectString) ->
    logging.log "Passing html result to next level handler, by redirecting to: " + redirectString
    res.writeHead 301,
      Location: redirectString

    res.end()
  convert = (localCopy, docLogger) ->
    name = localCopy.replace("../local-copies/pdf/", "").replace(".pdf", "") # extract the file name
    storage.store "pdf", name, localCopy, docLogger
    docMeta.storePdfMetaData localCopy, docLogger
    
    #docMeta.storePdfMetaData(name, localCopy)
    
    # 
    #		 * html2pdfEX doesn't have an option to pipe the output, so passing its output around
    #		 * is just a bit clumsier than it could have been. We use a directory structure one level up
    #		 * of this project, to store originals and conversion artifacts, as a way to share them with
    #		 * another web server running on the same server.
    #		 *
    #		 * For the output of html2pdfEX for a given input PDF document, we create a folder using its 
    #		 * randomly generated file name generated by html2pdfEX, and in it we store all the conversion 
    #		 * outputs for that file - the html, and accompanying files such as css, fonts, images, 
    #		 * and javascript that the html2pdfEX output needs to have. 
    #		 
    logging.log "Starting the conversion from pdf to html"
    util.timelog "Conversion to html"
    
    #res.send('Please wait...'');
    execCommand = executable + " "
    
    #outFileName = name + '.html'
    outFolder = "../local-copies/" + "html-converted/"
    execCommand += localCopy + " " + executalbeParams + " " + "--dest-dir=" + outFolder + "/" + name
    logging.log execCommand
    exec execCommand, (error, stdout, stderr) ->
      logging.log executable + "'s stdout: " + stdout
      logging.log executable + "'s stderr: " + stderr
      if error isnt null
        logging.log executable + "'sexec error: " + error
      else
        
        # KEEP THIS FOR LATER: redirectToShowHtml('http://localhost:8080/' + 'serve-original-as-html/' + name + "/" + outFileName)
        # redirectToShowRaw('http://localhost/' + 'extract' +'?file=' + name + "/" + outFileName)
        util.timelog "Conversion to html"
        redirectToExtract "http://localhost/" + "extract" + "?" + "name=" + name + "&" + "docLogger=" + docLogger

  inkUrl = req.query.tempLocation
  baseFileName = inkUrl.replace("https://www.filepicker.io/api/file/", "")
   
  
  # Initialize logger for this document
  docLogger = new winston.Logger
  docLoggername = baseFileName + '.log'
  docLogger.add(winston.transports.File, {filename: docLoggername})
  #docLogger = new (winston.Logger)({transports: [new (winston.transports.File)({filename: 'ffff'})]})
  console.log('Logging handling for ' + baseFileName + ' in ' + docLoggername)

  fetch(inkUrl, baseFileName, convert)  # fetch the upload and pass control to the convert function
