// Generated by CoffeeScript 1.4.0
var css, filterImages, html, model, output, soup, timer, util;

require("fs");

util = require("../util");

timer = require("../timer");

css = require("../css");

html = require("../html");

model = require("../model");

soup = require("../soup");

output = require("../output");

filterImages = function(ourDivRepresentation) {
  var div, filtered, _i, _len;
  filtered = [];
  for (_i = 0, _len = ourDivRepresentation.length; _i < _len; _i++) {
    div = ourDivRepresentation[_i];
    if (!util.startsWith(div.text, "<img ")) {
      filtered.push(div);
    }
  }
  return filtered;
};

exports.go = function(req, res) {
  var div, divsAndStyles, name, outputHtml, path, rawHtml, rawRelevantDivs, realStyles, tokensAndStyles, _i, _len;
  timer.start('Extraction from html stage A');
  path = '../local-copies/' + 'html-converted/';
  name = req.query.name;
  rawHtml = fs.readFileSync(path + name + '/' + name + ".html").toString();
  realStyles = css.simpleFetchStyles(rawHtml, path + name + '/');
  rawRelevantDivs = html.removeOuterDivs(rawHtml);
  divsAndStyles = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = rawRelevantDivs.length; _i < _len; _i++) {
      div = rawRelevantDivs[_i];
      _results.push(html.representDiv(div));
    }
    return _results;
  })();
  divsAndStyles = filterImages(divsAndStyles);
  for (_i = 0, _len = divsAndStyles.length; _i < _len; _i++) {
    div = divsAndStyles[_i];
    html.stripSpanWrappers(div);
  }
  tokensAndStyles = (function() {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = divsAndStyles.length; _j < _len1; _j++) {
      div = divsAndStyles[_j];
      _results.push(html.tokenizeWithStyle(div));
    }
    return _results;
  })();
  timer.end('Extraction from html stage A');
  util.logObject(tokensAndStyles);
  timer.start('Extraction from html stage B');
  soup.build(divsAndStyles);
  timer.end('Extraction from html stage B');
  outputHtml = "aaa";
  return output.serveOutput(outputHtml, name, res);
};
