// Generated by CoffeeScript 1.6.3
var fs, logging, storage, util;

util = require('../util');

storage = require('../storage');

logging = require('../logging');

fs = require('fs');

exports.go = function(req, res) {
  var name, pdfBytes, serve;
  serve = function(pdfBytes) {
    console.log(pdfBytes);
    if (pdfBytes) {
      /*
      fs.writeFile(outputFile, outputHtml, (err) -> 
        
        if err?
          res.send(500)
          throw err)
      */

      console.info('Sending response....');
      util.timelog('serving original pdf');
      res.setHeader('Content-Type', 'application/pdf');
      res.end(pdfBytes);
      return util.timelog('serving original pdf');
    }
  };
  if (req.session.name != null) {
    name = req.session.name;
    console.log(name);
    return pdfBytes = storage.fetch('pdf', name, serve);
  } else {
    console.error('session does not contain the name parameter');
    return res.send(500);
  }
};
