// Generated by CoffeeScript 1.6.3
var css, logging, util;

util = require('../util');

logging = require('../logging');

css = require('../css');

exports.go = function(req, res) {
  var paragraphOpeningDelimitation, tokenSequence, tokenSequenceSerialized, tokens, x, _i, _len;
  if (req.session.tokens == null) {
    return;
  }
  util.timelog("handling client ajax request for " + req.session.name);
  tokens = req.session.tokens;
  tokenSequence = [];
  paragraphOpeningDelimitation = {
    metaType: 'paragraphBreak'
  };
  for (_i = 0, _len = tokens.length; _i < _len; _i++) {
    x = tokens[_i];
    if (x.metaType === 'regular') {
      if (x.paragraph === 'opener') {
        tokenSequence.push(paragraphOpeningDelimitation);
      }
    }
    tokenSequence.push(x);
  }
  util.timelog('pickling');
  tokenSequenceSerialized = JSON.stringify(tokenSequence);
  util.timelog('pickling');
  console.log("" + tokens.length + " tokens pickled into " + tokenSequenceSerialized.length + " long bytes stream");
  console.log("pickled size to tokens ratio: " + (parseFloat(tokenSequenceSerialized.length) / tokens.length));
  res.end(tokenSequenceSerialized);
  return util.timelog("handling client ajax request for " + req.session.name);
};
