// Generated by CoffeeScript 1.6.3
var docsDataDir, fs, getPair, jsdiff, logging, util;

fs = require('fs');

util = require('../util/util');

logging = require('../util/logging');

jsdiff = require('diff');

docsDataDir = require('../data/dataWriter').docsDataDir;

getPair = function(inputFileName, dataType) {
  var docDataDir, relevantDataFiles;
  docDataDir = docsDataDir + '/' + inputFileName + '/';
  relevantDataFiles = fs.readdirSync(docDataDir).filter(function(dataFileName) {
    return dataFileName.indexOf(dataType) === 0;
  });
  if (relevantDataFiles.length > 1) {
    relevantDataFiles.sort().reverse();
    return relevantDataFiles.slice(0, 2).map(function(dataFileName) {
      return docDataDir + dataFileName;
    });
  }
  return void 0;
};

exports.diff = function(inputFileName, dataType) {
  var filesContent, pair;
  logging.logYellow('before diff');
  pair = getPair(inputFileName, dataType);
  if (pair != null) {
    filesContent = pair.map(function(file) {
      return fs.readFileSync(file, {
        encoding: 'utf8'
      });
    });
    console.log(filesContent[0]);
    console.log(filesContent[1]);
    jsdiff.diffLines(filesContent[0], filesContent[1]).forEach(function(line) {
      return console.log(line);
    });
    return logging.logYellow('after diff');
  }
};
