// Generated by CoffeeScript 1.6.3
var fs, logging, outputTemplate, util;

util = require('./util/util');

logging = require('./util/logging');

fs = require('fs');

outputTemplate = fs.readFileSync('outputTemplate/template.html').toString();

exports.serveViewerTemplate = function(res, docLogger) {
  docLogger.info('Sending response....');
  util.timelog('from upload to serving', docLogger);
  return res.sendfile('template.html', {
    root: 'outputTemplate/'
  });
};

exports.serveOutput = function(name, res, docLogger) {
  var outputFile, outputHtml;
  util.timelog('Saving serialized output to file');
  outputFile = '../local-copies/' + 'output/' + name + '.html';
  outputHtml = outputTemplate;
  return fs.writeFile(outputFile, outputHtml, function(err) {
    if (err != null) {
      res.send(500);
      throw err;
    }
    util.timelog('Saving serialized output to file', docLogger);
    docLogger.info('Sending response....');
    util.timelog('from upload to serving', docLogger);
    return res.sendfile(name + '.html', {
      root: '../local-copies/' + 'output/'
    });
  });
};
