// Generated by CoffeeScript 1.6.3
var dataWriter, exec, logging, util;

util = require('../util/util');

logging = require('../util/logging');

dataWriter = require('../data/dataWriter');

exec = require('child_process').exec;

exports.storePdfMetaData = function(name, localCopy, docLogger) {
  var execCommand;
  util.timelog(name, "Getting pdf file metadata using pdfinfo");
  execCommand = 'pdfinfo -meta' + ' ';
  execCommand += '"' + localCopy + '"';
  return exec(execCommand, function(error, stdout, stderr) {
    var meta;
    dataWriter.write(name, 'pdfMeta', execCommand + "'s stdout: \n" + stdout);
    dataWriter.write(name, 'pdfMeta', execCommand + "'s stderr: \n" + stderr);
    if (error !== null) {
      return dataWriter.write(name, 'pdfMeta', execCommand + "'sexec error: " + error);
    } else {
      util.timelog(name, "Getting pdf file metadata using pdfinfo", docLogger);
      return meta = {
        'raw': stdout,
        'stderr': stderr
      };
    }
  });
};
