// Generated by CoffeeScript 1.6.3
var storeCmdOutput;

storeCmdOutput = require('../util/storeCmdOutput');

exports.storePdfMetaData = function(name, localCopy, docLogger) {
  var params;
  params = {
    execCommand: 'pdfinfo -meta',
    writerType: 'pdfMeta',
    description: 'Getting pdf file metadata using pdfinfo'
  };
  return storeCmdOutput(name, localCopy, docLogger, params);
};

exports.storePdfFontsSummary = function(name, localCopy, docLogger) {
  var params;
  params = {
    execCommand: 'pdffonts',
    writerType: 'pdfFonts',
    description: 'Getting pdf fonts summary using pdffonts (1 of 2)'
  };
  storeCmdOutput(name, localCopy, docLogger, params);
  params = {
    execCommand: 'pdffonts -subst',
    writerType: 'pdfFonts',
    description: 'Getting pdf fonts summary using pdffonts (2 of 2)'
  };
  return storeCmdOutput(name, localCopy, docLogger, params);
};
