// Generated by CoffeeScript 1.6.3
var JATSOutDir, convert, dataOutDir, extract, fetch, fs, getFromUrl, initOutDirs, logging, nconf, textOutDir, util, winston;

convert = require('./convert');

extract = require('./extract');

util = require('../util/util');

getFromUrl = require('request');

fs = require('fs');

winston = require('winston');

logging = require('../util/logging');

nconf = require('nconf');

dataOutDir = nconf.get("locations")["pdf-extraction"]["asData"];

textOutDir = nconf.get("locations")["pdf-extraction"]["asText"];

JATSOutDir = nconf.get("locations")["pdf-extraction"]["asJATS"];

fetch = function(inkUrl, outFile, docLogger, req, res, callOnSuccess) {
  var download;
  return download = getFromUrl(inkUrl, function(error, response, body) {
    if (!error && response.statusCode === 200) {
      return callOnSuccess(outFile, docLogger, req, res);
    } else {
      console.log("fetching from InkFilepicker returned http status " + response.statusCode);
      if (error) {
        return docLogger.info("fetching from InkFilepicker returned error " + error);
      }
    }
  }).pipe(fs.createWriteStream(outFile));
};

initOutDirs = function(baseFileName) {
  util.mkdirRecursive(dataOutDir);
  util.mkdirRecursive(textOutDir);
  return util.mkdirRecursive(JATSOutDir);
};

exports.go = function(req, res) {
  var baseFileName, context, docLogger, fullFileName, inkUrl, outFile, runID;
  if (req.query.localLocation != null) {
    if (req.query.runID) {
      runID = req.query.runID;
    } else {
      runID = util.simpleGenerateRunID();
      logging.logRed("Augmenting request with runID " + runID);
    }
    fullFileName = req.query.localLocation;
    baseFileName = fullFileName.substring(fullFileName.lastIndexOf('/') + 1).replace('.pdf', '');
    context = {
      runID: runID,
      name: baseFileName
    };
    logging.logGreen("Started handling input file: " + fullFileName + ". Given run id is: " + context.runID);
    docLogger = util.initDocLogger(baseFileName);
    docLogger.info('logger started');
    initOutDirs(baseFileName);
    convert.go(context, fullFileName, docLogger, req, res);
    return;
  }
  if (req.query.inkUrl != null) {
    inkUrl = req.query.inkUrl;
    baseFileName = inkUrl.replace('https://www.filepicker.io/api/file/', '');
    docLogger = util.initDocLogger(baseFileName);
    docLogger.info('logger started');
    req.session.docLogger = docLogger;
    outFile = setOutFile(baseFileName);
    fetch(inkUrl, outFile, docLogger, req, res, convert.go);
    return;
  }
  logging.logRed("Bad request");
  return res.send(500);
};
