// Generated by CoffeeScript 1.6.3
var sampletext;

sampletext = '<!DOCTYPE html>\
    <html>\
      <head>\
        <meta charset="utf8"/>\
        <title>Page Title</title>\
      </head>\
      <body>\
        <a href="https://github.com/ForbesLindesay">\
          <img src="/static/forkme.png" alt="Fork me on GitHub">\
        </a>\
        <div class="row">\
          <div class="large-12 columns">\
            <h1 id="page-title">Page Title</h1>\
            <p>This is a demo page</p>\
          </div>\
        </div>\
        <script src="/static/client.js"></script>\
      </body>\
    </html>';
