// Generated by CoffeeScript 1.6.3
var Primus, http, logging, out, primus, server;

logging = require('./util/logging');

'use strict';

out = __dirname + '/public/javascripts' + '/primusClientLib.js';

logging.log('Building primus client library to be served to the client as ' + out);

http = require("http");

Primus = require('primus');

server = require('http').createServer();

primus = new Primus(server, {
  transformer: 'websockets'
});

primus.library();

primus.save(out);
