// Generated by CoffeeScript 1.6.3
var purge, wait;

purge = function() {
  var r;
  r = require('./rdbms');
  return r.reinit();
};

wait = 5;

console.log("");

console.log("ATTENTION!!! if not interupted the app rdbms will be purged in " + wait + " seconds");

console.log("");

setTimeout(purge, wait * 1000);
