// Generated by CoffeeScript 1.6.3
var connect, connection, docTables, exec, init, maxDbStrLength, purge, reinit, tables;

exec = require('../../util/exec');

docTables = [
  {
    name: 'sentences'
  }, {
    name: 'headers'
  }
];

docTables.forEach(function(table) {
  return table.type = 'docTable';
});

tables = docTables;

maxDbStrLength = 20000;

connection = {
  host: 'localhost',
  user: 'articlio',
  database: 'articlio',
  charset: 'utf8'
};

exports.connect = connect = function() {
  var knex;
  return knex = require("knex")({
    dialect: "mysql",
    connection: process.env.DB_CONNECTION_STRING || connection
  });
};

purge = function() {
  var conn;
  conn = connect();
  return tables.forEach(function(table) {
    return conn.schema.dropTableIfExists(table.name);
  });
};

init = function() {
  var conn, table, _i, _len;
  conn = connect();
  for (_i = 0, _len = tables.length; _i < _len; _i++) {
    table = tables[_i];
    conn.schema.createTable(table.name, function(newTable) {
      newTable.increments('id');
      if (table.type === 'docTable') {
        newTable.string('docName');
        newTable.string('text', maxDbStrLength);
        return newTable.string('runID');
      }
    })["catch"](function(error) {
      console.error(error);
      return console.error('database reinitialization failed');
    });
  }
  return console.log('database ready for action');
};

exports.reinit = reinit = function() {
  return exec('src/storage/rdbms/rdbms-recreate.sh', null, function(success) {
    if (success) {
      console.log('database and database user clean and ready');
      return init();
    } else {
      return console.error('database reinitialization failed - could not recreate database or database user');
    }
  });
};
