// Generated by CoffeeScript 1.6.3
var purge, r, wait;

r = require('./rdbms');

purge = function() {
  return r.reinit();
};

wait = 2;

console.log("");

console.log("ATTENTION!!! if not interupted the app rdbms will be purged in " + wait + " seconds");

console.log("");

setTimeout(purge, wait * 1000);
