// Generated by CoffeeScript 1.6.3
var Promise, analytic, assert, createColumn, exec, fs, lastRun, logging, rdbms, util;

assert = require('assert');

util = require('./util/util');

logging = require('./util/logging');

analytic = require('./util/analytic');

rdbms = require('./storage/rdbms/rdbms');

fs = require('fs');

Promise = require('bluebird');

exec = Promise.promisify(require('./util/exec'));

lastRun = function() {};

knex('runIDs').max('order').then(function(result) {
  lastRun = getQuerySingleResult(result);
  if (!lastRun) {
    throw 'No data found';
  }
  return knex.select('runID').from('runIDs').where({
    order: lastRun
  });
});

createColumn = function(table, column) {
  return knex.schema.hasTable(table, column).then(function(exists) {
    if (!exists) {
      return table(table).create(column);
    }
  })["catch"](function(error) {
    logging.logYellow(error);
    return logging.logYellow("failed creating column " + column + " in table " + table);
  });
};

createColumn('grading', 'fluff');
