// Generated by CoffeeScript 1.6.3
var analytic, assert, fs, logging, rdbms, util;

assert = require('assert');

fs = require('fs');

util = require('./util/util');

logging = require('./util/logging');

analytic = require('./util/analytic');

rdbms = require('./storage/rdbms/rdbms');

rdbms.query();
