// Generated by CoffeeScript 1.4.0
var directory, filename, fs, host, http, httpCallBack, nconf, timer, _i, _len, _ref;

http = require("http");

fs = require("fs");

nconf = require("nconf");

timer = require("../../timer");

nconf.argv().env();

nconf.defaults({
  host: "localhost"
});

host = nconf.get("host");

console.log("host to test: " + nconf.get("host"));

directory = '../local-copies/html-converted/';

_ref = fs.readdirSync(directory);
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  filename = _ref[_i];
  if (filename !== '.gitignore') {
    httpCallBack = (function(filename) {
      return function(res) {
        timer.end('server response for ' + filename);
        return console.log('server response for ' + filename + ' is:   ' + res.statusCode);
      };
    })(filename);
    console.log("requesting " + directory + filename);
    timer.start('server response for ' + filename);
    http.get('http://' + host + '/extract?name=' + filename, httpCallBack);
  } else {
    console.log('skipping .gitignore');
  }
}
