// Generated by CoffeeScript 1.6.3
var directory, filename, fs, host, http, httpCallBack, nconf, requests, responses, timer, _i, _len, _ref;

http = require("http");

fs = require("fs");

nconf = require("nconf");

timer = require("../../timer");

nconf.argv().env();

nconf.defaults({
  host: "localhost"
});

host = nconf.get("host");

console.log("host to test: " + nconf.get("host"));

http.globalAgent.maxSockets = 1000;

directory = '../local-copies/pdf/';

requests = 0;

responses = 0;

_ref = fs.readdirSync(directory);
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  filename = _ref[_i];
  if (fs.statSync(directory + filename).isFile()) {
    if (filename !== '.gitignore') {
      requests += 1;
      httpCallBack = (function(filename) {
        return function(res) {
          responses += 1;
          timer.end('server response for ' + filename);
          console.log('server response for ' + filename + ' is:   ' + res.statusCode);
          return console.log(responses + ' responses out of ' + requests + ' requests received thus far');
        };
      })(filename);
      console.log("requesting " + directory + filename);
      timer.start('server response for ' + filename);
      http.get('http://' + host + '/handleInputFile?' + 'localLocation=' + filename, httpCallBack);
    } else {
      console.log('skipping .gitignore');
    }
  } else {
    console.log('skipping subdirectory ' + filename);
  }
}
